name: idream
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-265.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # FIREBASE
  firebase: ^9.0.2
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.15
  firebase_database: ^9.0.12
  # stage management
  flutter_bloc: ^8.0.1

  #Font lib
  google_fonts: ^2.3.2

  # local database
  hive: ^2.1.0
  hive_flutter: ^1.1.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  build_runner: ^2.1.10

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
